server:
  port: 8082

so:
  db:
    database: so-knowledge
minio:
  endpoint: http://192.168.220.100:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucket:
    files: so-document

logging:
  level:
    com.cqf.knowledge.mapper: debug